name = "EpiEconShocks"
uuid = "d5106ebc-8f76-4abe-9d9c-e2e957300c8c"
authors = ["Imperial College London"]
version = "1.0.0-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
